# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  test:
    parameters:
      v:
        type: string
        default: "lts"
    docker:
      - image: cimg/node:<< parameters.v >>
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v<< parameters.v >>-npm-deps-{{ checksum "package-lock.json" }}
            - v<< parameters.v >>-npm-deps-
      - run: npm ci
      - save_cache:
          key: v<< parameters.v >>-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm test
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    parameters:
      v:
        type: string
        default: "lts"
    docker:
      - image: cimg/node:<< parameters.v >>
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish


  token-test:
    steps:
      - run:
        command: echo "Hello world"
workflows:
  version: 2
  test:
    jobs:
      - test:
          name: test_lts
          v: "lts"
      - test:
          name: test_current
          v: "18.0.0"
  test_and_deploy:
    jobs:
      - token-test
        context: publish-npm

      - test:
          name: test_lts
          v: "lts"
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - deploy:
          context: publish-npm
          v: "lts"
          requires:
            - test_lts
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
